// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7zSPxbV6S4gIi2n9x0CE-mbzjUUGYSNY',
    appId: '1:696450645574:web:f4eb03cb7725e429635447',
    messagingSenderId: '696450645574',
    projectId: 'personalproject-gymapp',
    authDomain: 'personalproject-gymapp.firebaseapp.com',
    databaseURL: 'https://personalproject-gymapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personalproject-gymapp.appspot.com',
    measurementId: 'G-KV8KCN620B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB3YVieLWZg5OtIUsad8_0talyatDTtuo',
    appId: '1:696450645574:android:bad4798488db5fd9635447',
    messagingSenderId: '696450645574',
    projectId: 'personalproject-gymapp',
    databaseURL: 'https://personalproject-gymapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personalproject-gymapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC3iCrhKJQAKebK0p4UkK-62cGDm8fnJc',
    appId: '1:696450645574:ios:c6b2a8199085850d635447',
    messagingSenderId: '696450645574',
    projectId: 'personalproject-gymapp',
    databaseURL: 'https://personalproject-gymapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personalproject-gymapp.appspot.com',
    iosClientId: '696450645574-8n7mrggiu3p41jmvrbn1r11r52ocv4p7.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymWebNew',
  );
}
